# Numpy Field Guide

Numpy arrays are fast and powerful.   Try to use these instead of 
iterating through elements of a Python list whenever applicable since
the underlying numpy library is compiled from C and as such is much
faster than the interpreted python.

In [1]:
import numpy as np
import matplotlib

## Create a range array

Create an array from 0 to `n`:
`np.arange(n+1)`

In [4]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Range between two values:

In [5]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Array of zeroes:

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Multi dimensional array (5x5):

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In general:
`np.zeros((rows, columns))`

In [11]:
rows = 3
columns = 2
np.zeros((rows, columns))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Using `linspace` can be useful for the inputs to graphs.  It can generate
a range of `count` between `min` and `max` inclusive:

In [14]:
min = 0
max = 10
count = 100
np.linspace(min, max, count)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

## Indexing

In [15]:
arr = np.arange(1, 11)

First element:

In [16]:
arr[0]

1

Last Element

In [17]:
arr[-1]

10

First 3 elements:

In [18]:
arr[0:3]

array([1, 2, 3])

All but last:

In [19]:
arr[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

All but first

In [20]:
arr[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

Second thrrough seventh element:

In [23]:
arr[1:7]

array([2, 3, 4, 5, 6, 7])

Perform math on the entire array at once:

In [24]:
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
arr-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [28]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

Element wise math between two arrays:

In [29]:
arr2 = np.arange(2, 12)

In [31]:
arr2 - arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
arr - arr2

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [33]:
arr + arr2

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

## Random Numbers

By default Numpy's `random.rand(n)` generates an array of number uniformly distributed
between 0 and 1:

In [36]:
np.random.rand(10)

array([0.50755925, 0.63226608, 0.83002359, 0.43597311, 0.21005645,
       0.59413882, 0.70312584, 0.83239984, 0.60586284, 0.00924682])

In [38]:
np.random.rand(2,3)

array([[0.49077245, 0.32119178, 0.16337794],
       [0.29829441, 0.25141549, 0.14262274]])

Generating normally distributed random numbers.   By default, these
will generate numbers with a mean of 0 and a standard deviation of 1
(note: the size of the array is specified by `size` keyword argument:

In [41]:
np.random.normal(size=20)

array([ 0.8868281 ,  0.61776828, -0.82365507,  0.42640967,  0.37094591,
       -1.29171831,  0.23836748,  0.24359742, -0.0715745 , -0.29393079,
        1.07354375,  3.06931855, -0.4124962 ,  0.42228278, -1.61585573,
        0.17456526,  0.21108769, -0.36698095, -0.55300418,  0.33236261])

Multidimensional arrays can be genrated as well:

In [46]:
np.random.normal(size=(20, 3))

array([[ 0.38950949,  0.48909338,  0.52899905],
       [ 0.35937008, -1.23190062, -1.28693639],
       [ 2.16376124, -0.03623493, -1.12690428],
       [ 0.17288041,  0.76191217, -1.15093363],
       [ 0.16712289,  0.89423623, -1.02652328],
       [-0.06696562,  0.79811667,  0.84705229],
       [-0.98918545,  0.26631521, -0.21204829],
       [ 0.5017695 , -0.51137934,  0.43125589],
       [ 1.05246426,  0.24651844,  0.74122639],
       [ 0.04693196,  2.03785698, -0.31598714],
       [ 0.63713497,  1.03020999,  0.76295854],
       [ 0.01485243,  0.67752584,  1.1461894 ],
       [ 0.788035  , -1.46087151,  0.67419501],
       [-1.33185859,  0.53027443,  0.86371345],
       [-1.22367533, -1.21171784, -0.77968982],
       [-0.89210598,  0.25021248, -1.11153093],
       [ 2.35930677,  2.54037372, -1.33196948],
       [-0.06697957,  0.84514935,  1.70984126],
       [-1.28840806,  1.56596487,  0.8476062 ],
       [-0.75742777,  0.14574366,  0.6311062 ]])

To generate numbers with a specific center (mean) and spread (standard deviation), use 
`loc` to set the mean and `scale` to set the standard deviation.

In [44]:
np.random.normal(loc=10, scale=3, size=20)

array([ 9.21968316, 12.72915984,  8.69414009, 12.22692247, 14.21690476,
        9.8370603 ,  4.60793415,  9.56162344,  6.88545907, 11.6802051 ,
       14.77439486,  9.05918799,  8.00641704, 13.21039964, 15.37774673,
       11.72769274, 10.87179109,  5.4357937 ,  9.2260014 ,  5.41769724])