# Quantum Computing Math

My notes on quantum computing math based on:

https://www.youtube.com/watch?v=F_Riqjdh2oM

using sympy and numpy.

In [95]:
import numpy as np
import sympy as sp
from sympy.physics.quantum import TensorProduct

## Representation of Bits in Quantum

To represent a 0 bit:

$
\displaystyle \left[\begin{matrix}1\\0\end{matrix}\right]
$

To representa 1 bit:

$
\displaystyle \left[\begin{matrix}0\\1\end{matrix}\right]
$

### brak-et notation:
Shorthand for the matrix representation:

1-bit
$
|1>
$

0-bit:
$
|0>
$

In numpy as:

In [2]:
q0 = np.array([1, 0])
q1 = np.array([0, 1])

## Matrix Representation of classic single-bit operations

Just to show how classic operations on the bit representations would be done,
the following are the matrix representation of the classic single-bit operations:

Constant 1:
$
\displaystyle \left[\begin{matrix}0 & 0\\1 & 1\end{matrix}\right]
$

Constant 0:
$
\displaystyle \left[\begin{matrix}1 & 1\\0 & 0\end{matrix}\right]
$

Negate:
$
\displaystyle \left[\begin{matrix}0 & 1\\1 & 0\end{matrix}\right]
$

Identity:
$
\displaystyle \left[\begin{matrix}1 & 0\\0 & 1\end{matrix}\right]
$

In [22]:
set1 = np.array([[0,0], [1,1]])
set0 = np.array([[1,1], [0,0]])
negate = np.array([[0, 1], [1, 0]])
identity = np.array([[1, 0], [0, 1]])

### Using tensor products to perform operations:

In [33]:
display(sp.Matrix(np.tensordot(set1, q0, axes=1)))
sp.Matrix(np.tensordot(set1, q1, axes=1))

Matrix([
[0],
[1]])

Matrix([
[0],
[1]])

In [34]:
display(sp.Matrix(np.tensordot(set0, q0, axes=1)))
sp.Matrix(np.tensordot(set0, q1, axes=1))

Matrix([
[1],
[0]])

Matrix([
[1],
[0]])

In [35]:
display(sp.Matrix(np.tensordot(negate, q0, axes=1)))
sp.Matrix(np.tensordot(negate, q1, axes=1))

Matrix([
[0],
[1]])

Matrix([
[1],
[0]])

In [36]:
display(sp.Matrix(np.tensordot(identity, q0, axes=1)))
sp.Matrix(np.tensordot(identity, q1, axes=1))

Matrix([
[1],
[0]])

Matrix([
[0],
[1]])

## Quantum Operations

Quantum operations all have two properties:
1. They are always reversible
2. They are always reversible by the same operation.

Note: constant operations are not reversible.

### Representing multiple q-bits

To represent multiple q-bits, we take the classical representation of the bits and 
tensor product them together.


Note: with numpy, we always need to reshape to get back to single matrix representation.

Notice how the position of the 1 in the following matricies switches to represent 
combinations of two qbits:

$ |00> $

In [47]:
sp.Matrix(np.tensordot(q0, q0, axes=0).reshape(4))

Matrix([
[1],
[0],
[0],
[0]])

$ |01> $

In [48]:
sp.Matrix(np.tensordot(q0, q1, axes=0).reshape(4))

Matrix([
[0],
[1],
[0],
[0]])

$ |10> $

In [49]:
sp.Matrix(np.tensordot(q1, q0, axes=0).reshape(4))

Matrix([
[0],
[0],
[1],
[0]])

$ |11> $

In [50]:
sp.Matrix(np.tensordot(q1, q1, axes=0).reshape(4))

Matrix([
[0],
[0],
[0],
[1]])

Note how the number of digits expands exponentially as we add another q-bit - this hints at 
the power of quantum computing.

In [56]:
sp.Matrix(np.tensordot(q0, np.tensordot(q0, q1, axes=0).reshape(4), axes=0).reshape(8))

Matrix([
[0],
[1],
[0],
[0],
[0],
[0],
[0],
[0]])

## CNOT operation

* Operates on pairs of bits - the first is the control bit. The second is the target bit.
* If the control bit is 1, the second bit is flipped
* If the control bit is 0, the second bit is unchanged
* The control bit is always unchanged
* Most significant is the control, least significant is the target

$
\displaystyle \left[\begin{matrix}1 & 0 & 0 & 0\\0 & 1 & 0 & 0\\0 & 0 & 0 & 1\\0 & 0 & 1 & 0\end{matrix}\right]
$

In [60]:
cnot = np.array([[1,0,0,0],
                 [0,1,0,0],
                 [0,0,0,1],
                 [0,0,1,0]
                ])

Examples of cnot for different pairs of q-bits:

Note how the first two are unchanged and the second two are flipped.

In [72]:
qb00 = np.tensordot(q0, q0, axes=0).reshape(4)
qb01 = np.tensordot(q0, q1, axes=0).reshape(4)
qb10 = np.tensordot(q1, q0, axes=0).reshape(4)
qb11 = np.tensordot(q1, q1, axes=0).reshape(4)

display(sp.Matrix(np.tensordot(cnot, qb00, axes=1)))
display(sp.Matrix(np.tensordot(cnot, qb01, axes=1)))
display(sp.Matrix(np.tensordot(cnot, qb10, axes=1)))
display(sp.Matrix(np.tensordot(cnot, qb11, axes=1)))

Matrix([
[1],
[0],
[0],
[0]])

Matrix([
[0],
[1],
[0],
[0]])

Matrix([
[0],
[0],
[0],
[1]])

Matrix([
[0],
[0],
[1],
[0]])

## QBits

The classical bit representations so far are special cases of the Q-bit.   

QBits are vectors 

$$
\displaystyle \left[\begin{matrix}a\\b\end{matrix}\right]
$$

Such that
$$ 
||a||^2 + ||b||^2 = 1 
$$

* a and b can be complex numbers.
* We can now use negative or fractional numbers.

The following are example QBit values:

$
\displaystyle \left[\begin{matrix}\frac{1}{\sqrt{2}}\\\frac{1}{\sqrt{2}}\end{matrix}\right]
$

$
\displaystyle \left[\begin{matrix}\frac{1}{2}\\\frac{1}{\sqrt[3]{2}}\end{matrix}\right]
$

$
\displaystyle \left[\begin{matrix}-1\\0\end{matrix}\right]
$


$
\displaystyle \left[\begin{matrix}\frac{1}{\sqrt{2}}\\\frac{-1}{\sqrt{2}}\end{matrix}\right]
$

The fractional indicates superposition - partials of $ |1>$ and $ |0> $

QBits collapse to $|1>$ with a probability of $ ||a||^2 $ and collapse to $|0>$ with a probability of $ ||b||^2 $

The classical 

$ \displaystyle \left[\begin{matrix}0\\1\end{matrix}\right] $

has 100% chance to collapse to 1 and

$ \displaystyle \left[\begin{matrix}1\\0\end{matrix}\right] $

has 100% chance to collapse to 0.

As before, multiple QBits are represented by their tensor product.

In [103]:
a,b,c,d = sp.symbols("a b c d")
TensorProduct(sp.Matrix([a,b]), sp.Matrix([c, d]))

Matrix([
[a*c],
[a*d],
[b*c],
[b*d]])

In [88]:
sp.Matrix([sp.Rational(1,2), sp.Rational(1/2)])

Matrix([
[1/2],
[1/2]])

In [94]:
sp.Matrix([-1, 0])

Matrix([
[-1],
[ 0]])

## Hadamard Gate

$
\displaystyle \left[\begin{matrix}\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}}\\\frac{1}{\sqrt{2}} & \frac{-1}{\sqrt{2}}\end{matrix}\right]
$

In [110]:
H = np.array([
    [1/np.sqrt(2), 1/np.sqrt(2)], 
    [1/np.sqrt(2), -1/np.sqrt(2)]
])

Hadamard gate transitions a classical bit into superposition:

In [134]:
s0 = np.tensordot(H, q0, axes=1)
s0

array([0.70710678, 0.70710678])

Note for the $ |1> $ bit, the negative - this ensures the operation
is reversible.

In [139]:
s1 = np.tensordot(H, q1, axes=1)
s1

array([ 0.70710678, -0.70710678])

And can transition out of superposition:

In [140]:
np.tensordot(H, s0, axes=1)

array([1., 0.])

In [141]:
np.tensordot(H, s1, axes=1)

array([0., 1.])