In [ ]:
import numpy as np
import matplotlib.pyplot as plt 
import seaborn

In [3]:
a = np.zeros((3,3))

In [4]:
b = np.array([3,3,3])

In [5]:
a + b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [6]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
b

array([3, 3, 3])

In [8]:
b+a

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [24]:
a = np.ones((3,3,3))

b = np.array([1,2,3])

In [25]:
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [29]:
c = a + b

In [34]:
c[0][2]

array([2., 3., 4.])